services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Application\:
        resource: '../../src/'
        exclude:
            - '../../src/Entity/'
            - '../../src/Kernel.php'

    App\Application\ServiceInterface\ApplicationLifecycleServiceInterface:
        alias: App\Application\Service\ApplicationLifecycleService
        public: true

    App\Application\ServiceInterface\ApplicationManifestServiceInterface:
        alias: App\Application\Service\ApplicationManifestService
        public: true

    App\Application\ServiceInterface\ApplicationDiagnosticsServiceInterface:
        alias: App\Application\Service\ApplicationDiagnosticsService
        public: true

    App\Application\ServiceInterface\ApplicationReportServiceInterface:
        alias: App\Application\Service\ApplicationReportService
        public: true

    App\Application\ServiceInterface\ApplicationAdminViewBuilderInterface:
        alias: App\Application\Service\ApplicationAdminViewBuilder
        public: true

    App\Application\ServiceInterface\ApplicationReadinessServiceInterface:
        alias: App\Application\Service\ApplicationReadinessService
        public: true

    App\Application\ServiceInterface\ApplicationHealthServiceInterface:
        alias: App\Application\Service\ApplicationHealthService
        public: true

    Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader:
        alias: doctrine.fixtures.loader
