apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: catalog
  namespace: argocd
spec:
  description: Catalog project
  sourceRepos:
    - '*'
  destinations:
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
