framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    form: true
    csrf_protection: true
    validation:
        email_validation_mode: html5
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    router:
        utf8: true
