apiVersion: v1
kind: Service
metadata:
  name: billing
  namespace: smartresponsor
spec:
  selector:
    app: billing
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
