apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: smartresponsor
spec:
  selector:
    app: orchestrator
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
