apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartcloud-api
  namespace: smartcloud
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.smartcloud.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smartcloud-api
                port:
                  number: 8090
