<?php

declare(strict_types=1);

namespace App\Applicating\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260824184100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add per-environment application runtime assignment state.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE application_runtime_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, environment VARCHAR(40) NOT NULL, runtime_mode VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_application_runtime_assignment_application_id ON application_runtime_assignment (application_id)');
        $this->addSql('CREATE INDEX idx_application_runtime_assignment_environment ON application_runtime_assignment (environment)');
        $this->addSql('CREATE INDEX idx_application_runtime_assignment_mode ON application_runtime_assignment (runtime_mode)');
        $this->addSql('CREATE UNIQUE INDEX uniq_application_runtime_assignment ON application_runtime_assignment (application_id, environment)');
        $this->addSql('ALTER TABLE application_runtime_assignment ADD CONSTRAINT fk_application_runtime_assignment_application FOREIGN KEY (application_id) REFERENCES application_listing (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE application_runtime_assignment DROP CONSTRAINT fk_application_runtime_assignment_application');
        $this->addSql('DROP TABLE application_runtime_assignment');
    }
}
