receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_mib: 256
    spike_limit_mib: 128

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      resource:
        service.name: "service_name"
        service.version: "service_version"
      attributes:
        level: "log.severity"
        route: "http.route"
  logging:
    loglevel: info

service:
  telemetry:
    logs:
      level: "info"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [jaeger, logging]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [loki, logging]
