-- Developer Hub & SDK
CREATE TABLE IF NOT EXISTS devhub_api_keys (
  id BIGSERIAL PRIMARY KEY,
  developer_id TEXT NOT NULL,
  label TEXT NOT NULL,
  api_key TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  revoked_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS devhub_audit (
  id BIGSERIAL PRIMARY KEY,
  ts TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  event TEXT NOT NULL,
  actor TEXT NOT NULL,
  meta TEXT NOT NULL
);
