-- AI Feedback Queue
CREATE TABLE IF NOT EXISTS ai_feedback_queue (
  id BIGSERIAL PRIMARY KEY,
  ts TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  tenant_id TEXT NOT NULL,
  type TEXT NOT NULL,
  payload TEXT NOT NULL
);
