-- Neural Cloud Fabric
CREATE TABLE IF NOT EXISTS neural_agent_decisions (
  id BIGSERIAL PRIMARY KEY,
  ts TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  tenant_id TEXT NOT NULL,
  decision JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS neural_local_weights (
  id BIGSERIAL PRIMARY KEY,
  ts TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  tenant_id TEXT NOT NULL,
  weights JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS neural_fabric_updates (
  id BIGSERIAL PRIMARY KEY,
  ts TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  global_adjust NUMERIC NOT NULL
);
