apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "catalog.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "catalog.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
            - name: REDIS_DSN
              value: {{ .Values.env.REDIS_DSN | quote }}
            - name: JWT_SECRET
              value: {{ .Values.env.JWT_SECRET | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
