apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-secrets
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: catalog-secrets
      namespace: default
    type: Opaque
