name: qodana

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'config/**'
      - 'templates/**'
      - 'public/**'
      - 'tools/**'
      - 'docs/**'
      - 'composer.json'
      - 'composer.lock'
      - 'qodana.yaml'
      - '.github/workflows/qodana.yml'
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'config/**'
      - 'templates/**'
      - 'public/**'
      - 'tools/**'
      - 'docs/**'
      - 'composer.json'
      - 'composer.lock'
      - 'qodana.yaml'
      - '.github/workflows/qodana.yml'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          upload-result: true
          artifact-name: applicating-qodana-report
