name: test
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2', '8.3', '8.4' ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/ecs check
      - run: vendor/bin/rector process --dry-run
      - run: vendor/bin/phpunit --coverage-text --min=90
